source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SAC Digital Lite' do
    pod 'Alamofire', '~> 4.7'
    pod 'paper-onboarding'
    pod 'MaterialComponents/ShadowElevations'
    pod 'lottie-ios'
    pod 'Charts'
    pod 'ScrollableGraphView'
    pod 'ObjectMapper', '~> 3.2'
    pod ‘SwiftMaskText’
end